/// Generated by AssetsRefGenerator on 2020/11/02
class Res {
  static const String corona_map_anim = "assets/anim/corona_map_anim.json";
  static const String hear_anim = "assets/anim/hear_anim.json";
  static const String location_anim = "assets/anim/location_anim.json";
  static const String placeholder_anim = "assets/anim/placeholder_anim.json";
  static const String sanitizer_anim = "assets/anim/sanitizer_anim.json";
  static const String sneezing_anim = "assets/anim/sneezing_anim.json";
  static const String social_distancing = "assets/anim/social_distancing.json";
  static const String splash_anim = "assets/anim/splash_anim.json";
  static const String wash_hands_anim = "assets/anim/wash_hands_anim.json";
  static const String wear_anim = "assets/anim/wear_anim.json";
  static const String work_from_home_anim = "assets/anim/work_from_home_anim.json";
  static const String location = "assets/icons/location.svg";
  static const String menu = "assets/icons/menu.svg";
  static const String tip = "assets/icons/tip.svg";
  static const String Chart = "assets/images/Chart.png";
  static const String cough = "assets/images/cough.png";
  static const String dizzy = "assets/images/dizzy.png";
  static const String fever = "assets/images/fever.png";
  static const String mask = "assets/images/mask.png";
  static const String sneeze = "assets/images/sneeze.png";
  static const String sore_throat = "assets/images/sore_throat.png";
  static const String ar = "assets/translations/ar.json";
  static const String en = "assets/translations/en.json";
}
